import { UMKMFormData, UMKMProfile } from "../types";
import { apiClient } from "./api";
import { API_CONFIG } from "./api/config";

export class ProfileService {
  /**
   * Get all profiles for current user
   */
  static async getAllProfiles(): Promise<UMKMProfile[]> {
    try {
      const response = await apiClient.request(API_CONFIG.ENDPOINTS.PROFILES, {
        method: "GET",
        requireAuth: true,
      });

      if (response.success && response.data) {
        return response.data.map(this.transformProfile);
      }
      return [];
    } catch (error) {
      console.error("Error getting profiles:", error);
      return [];
    }
  }

  /**
   * Get profile by ID
   */
  static async getProfileById(id: string): Promise<UMKMProfile | null> {
    try {
      const response = await apiClient.request(
        `${API_CONFIG.ENDPOINTS.PROFILES}/${id}`,
        {
          method: "GET",
          requireAuth: true,
        }
      );

      if (response.success && response.data) {
        return this.transformProfile(response.data);
      }
      return null;
    } catch (error) {
      console.error("Error getting profile by ID:", error);
      return null;
    }
  }

  /**
   * Save profile (Create or Update)
   */
  static async saveProfile(profile: UMKMFormData | UMKMProfile): Promise<void> {
    try {
      const isUpdate = "id" in profile && profile.id;
      const endpoint = isUpdate
        ? `${API_CONFIG.ENDPOINTS.PROFILES}/${profile.id}`
        : API_CONFIG.ENDPOINTS.PROFILES;
      const method = isUpdate ? "PUT" : "POST";

      // Transform frontend data to backend format
      const payload = {
        namaUmkm: profile.namaUsaha,
        jenisUsaha: profile.jenisUsaha,
        deskripsi: profile.deskripsiUsaha,
        alamat: profile.alamatLengkap,
        kota: profile.kota,
        provinsi: profile.provinsi,
        kodePos: profile.kodePos,
        nib: profile.nib,
        telepon: profile.nomorKontak,
        email: profile.email,
        website: profile.website,
        fotoProfil: profile.fotoLogo,
        status: profile.status,
      };

      const response = await apiClient.request(endpoint, {
        method,
        body: payload,
        requireAuth: true,
      });

      if (!response.success) {
        throw new Error(response.message || "Gagal menyimpan profil");
      }
    } catch (error) {
      console.error("Error saving profile:", error);
      throw error;
    }
  }

  /**
   * Delete profile
   */
  static async deleteProfile(id: string): Promise<void> {
    try {
      const response = await apiClient.request(
        `${API_CONFIG.ENDPOINTS.PROFILES}/${id}`,
        {
          method: "DELETE",
          requireAuth: true,
        }
      );

      if (!response.success) {
        throw new Error(response.message || "Gagal menghapus profil");
      }
    } catch (error) {
      console.error("Error deleting profile:", error);
      throw error;
    }
  }

  /**
   * Update profile status
   */
  static async updateProfileStatus(
    id: string,
    status: UMKMProfile["status"]
  ): Promise<void> {
    try {
      // Assuming we can use the save/update endpoint for this
      const response = await apiClient.request(
        `${API_CONFIG.ENDPOINTS.PROFILES}/${id}`,
        {
          method: "PUT",
          body: { status },
          requireAuth: true,
        }
      );

      if (!response.success) {
        throw new Error(response.message || "Gagal mengupdate status profil");
      }
    } catch (error) {
      console.error("Error updating profile status:", error);
      throw error;
    }
  }

  /**
   * Convert UMKMProfile to UMKMFormData
   */
  static profileToFormData(profile: UMKMProfile): UMKMFormData {
    return {
      namaUsaha: profile.namaUsaha,
      jenisUsaha: profile.jenisUsaha,
      deskripsiUsaha: profile.deskripsiUsaha || "",
      alamatLengkap: profile.alamatLengkap,
      kota: profile.kota,
      provinsi: profile.provinsi,
      kodePos: profile.kodePos,
      nib: profile.nib,
      nomorKontak: profile.nomorKontak,
      email: profile.email || "",
      website: profile.website || "",
      fotoLogo: profile.fotoLogo,
    };
  }

  /**
   * Convert UMKMFormData to UMKMProfile
   */
  static formDataToProfile(formData: UMKMFormData): UMKMProfile {
    return {
      id: "", // Will be generated by backend
      ...formData,
      status: "pending",
      tanggalDaftar: new Date(),
    };
  }

  // Helper to transform backend data to frontend model
  private static transformProfile(data: any): UMKMProfile {
    return {
      id: String(data.id || ""),
      namaUsaha: data.namaUmkm || "Tanpa Nama Usaha",
      jenisUsaha: data.jenisUsaha || "Lainnya",
      deskripsiUsaha: data.deskripsi || "",
      alamatLengkap: data.alamat || "",
      kota: data.kota || "",
      provinsi: data.provinsi || "",
      kodePos: data.kodePos || "",
      nib: data.nib || "",
      nomorKontak: data.telepon || "",
      email: data.email || "",
      website: data.website || "",
      fotoLogo: data.fotoProfil,
      status: (["aktif", "non-aktif", "pending"].includes(data.status)
        ? data.status
        : "pending") as UMKMProfile["status"],
      tanggalDaftar: data.createdAt ? new Date(data.createdAt) : new Date(),
    };
  }
}
